name: sync upstream

on:
  schedule:
    # --     m h d(m) m d(w)
    - cron: '0 *   *  * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: identify
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: fetch upstream
        run: |
          git remote add upstream https://github.com/fortran-lang/stdlib.git
          git fetch upstream

      - name: merge upstream/master
        run: |
          git merge upstream/master --allow-unrelated-histories --no-edit

      - name: match upstream's commit message
        run: |
          MSG="$(git log -1 --pretty=%B upstream/master)"
          git commit --amend -m "$MSG"

      - name: commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push --force origin master
